# Generated by Django 2.2.4 on 2019-08-24 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190824_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='idade',
        ),
    ]
