# Generated by Django 2.2.4 on 2019-08-24 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190824_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='placamae',
            new_name='procecador',
        ),
    ]
