# Generated by Django 2.2.4 on 2019-08-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190824_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='placamae',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
