# Generated by Django 2.2.4 on 2019-08-24 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190824_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='user',
        ),
    ]
