# Generated by Django 2.2.4 on 2019-08-24 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_pedido_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='user',
        ),
    ]
