# Generated by Django 2.2.4 on 2019-08-24 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_pedido_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
