# Generated by Django 2.2.4 on 2019-08-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='user',
        ),
        migrations.AddField(
            model_name='pedido',
            name='memoria',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='placadevideo',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='placamae',
            field=models.CharField(default=3, max_length=50),
            preserve_default=False,
        ),
    ]
