# Generated by Django 2.2.4 on 2019-08-24 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_pedido_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='user',
        ),
    ]
