# Generated by Django 2.2.4 on 2019-08-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_pedido_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='pedido',
            field=models.ManyToManyField(to='core.Pedido'),
        ),
    ]
