# Generated by Django 2.2.4 on 2019-08-25 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_cliente_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='pedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='core.Cliente'),
            preserve_default=False,
        ),
    ]
