# Generated by Django 2.2.4 on 2019-08-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20190826_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memoria',
            name='qtd',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='memoria',
        ),
        migrations.AddField(
            model_name='pedido',
            name='memoria',
            field=models.ManyToManyField(related_name='memorias', to='core.Memoria'),
        ),
    ]
