# Generated by Django 2.2.4 on 2019-08-26 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20190826_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='memorias',
        ),
    ]
