# Generated by Django 2.2.4 on 2019-08-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_pedido_memorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='MemoriaPedido',
            field=models.ManyToManyField(related_name='mps', to='core.MemoriaPedido'),
        ),
    ]
