# Generated by Django 2.2.4 on 2019-08-28 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20190828_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='memoria',
            new_name='memorias',
        ),
    ]
