# Generated by Django 2.2.4 on 2019-08-31 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_pedido_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacaMae',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('processadores', models.CharField(max_length=50)),
                ('qtdeslots', models.IntegerField()),
                ('totaldememoria', models.IntegerField()),
                ('videoIntegrado', models.BooleanField()),
            ],
        ),
    ]
