# Generated by Django 2.2.4 on 2019-08-31 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20190831_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='placamae',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placamae', to='core.PlacaMae'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='procecador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procecador', to='core.Procecador'),
        ),
    ]
