# Generated by Django 2.2.4 on 2019-09-01 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20190831_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='procecador',
        ),
    ]
