# Generated by Django 2.2.4 on 2019-09-01 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_pedido_procecador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Procecador',
        ),
    ]
