# Generated by Django 2.2.4 on 2019-09-01 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_processador'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='processador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='procecador', to='core.Processador'),
            preserve_default=False,
        ),
    ]
