# Generated by Django 2.2.4 on 2019-10-21 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_pedido_processador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placamae',
            old_name='totaldememoria',
            new_name='total_memorias',
        ),
        migrations.RenameField(
            model_name='placamae',
            old_name='videoIntegrado',
            new_name='video_integrado',
        ),
    ]
