# Generated by Django 2.2.4 on 2019-10-21 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20191021_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='placadevideo',
            new_name='placa_de_video',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='placamae',
            new_name='placa_mae',
        ),
        migrations.RenameField(
            model_name='placamae',
            old_name='qtdeslots',
            new_name='qtd_eslots',
        ),
    ]
